<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.1.1 (Python 3.11.4 on win32)" generated="2024-10-24T10:30:00.917553" rpa="false" schemaversion="5">
<suite id="s1" name="Verify Invalid Login Csv Suite" source="c:\Mine\Company\Konsberg\HybridFramework\test\1__login_suite\4__verify_invalid_login_csv_suite.robot">
<test id="s1-t1" name="TC2" line="18">
<kw name="Log To Console" owner="BuiltIn">
<msg time="2024-10-24T10:30:01.257098" level="FAIL">Variable '${username}' not found.</msg>
<arg>${test_name}+${username}+${password}</arg>
<doc>Logs the given message to the console.</doc>
<status status="FAIL" start="2024-10-24T10:30:01.256085" elapsed="0.004522">Variable '${username}' not found.</status>
</kw>
<status status="FAIL" start="2024-10-24T10:30:01.254087" elapsed="0.006520">Variable '${username}' not found.</status>
</test>
<doc>This suite file validates valid login of the employee and admin
which connects to scenario SC_02 and test case TC02</doc>
<status status="FAIL" start="2024-10-24T10:30:00.924164" elapsed="0.336443"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Verify Invalid Login Csv Suite">Verify Invalid Login Csv Suite</stat>
</suite>
</statistics>
<errors>
<msg time="2024-10-24T10:30:01.241983" level="ERROR">[ DataDriver ] Error in robot file:
  File "c:\Mine\Company\Konsberg\HybridFramework\test\1__login_suite\4__verify_invalid_login_csv_suite.robot", line 0</msg>
<msg time="2024-10-24T10:30:01.241983" level="ERROR">In source file:
  File "c:\Mine\Company\Konsberg\HybridFramework\test\1__login_suite\..\..\test-data\invalid_login_data.csv", line 0</msg>
<msg time="2024-10-24T10:30:01.252954" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: AttributeError: No "Test Template" keyword found for first test case.</msg>
</errors>
</robot>
